spring:
  mail:
    host: smtp.qq.com
    username: 798358579@qq.com
    port: 465
    #授权码,在QQ邮箱客户端生成 修改成自己的  设置-账户-开启服务-获取授权码
    password: cwqicvqdetxqbeai
    default-encoding: UTF-8
    properties: 
      smtp: 
        auth: true
        starttls: 
          enable: true
          required: true
        timeout: 25000
#freemarker
#  freemarker:
#    template-loader-path: /static/template/
#    enabled: true
#    cache: false
#    charset: UTF-8
#    content-type: text/html
#    allow-request-override: false
#    check-template-location: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: false
#thymeleaf
  thymeleaf:
    prefix: classpath:/static/template/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet: 
      content-type: text/html
    cache: false
    
  resources:
    static-locations: classpath:/static,classpath:/static/templates/,classpath:/public,classpath:/resources,classpath:/META-INF/resources